### ISSUE TITLE
The emails are not sent to the RECIPIENT

### ISSUE THREAD

**Issue by liviust** [matthiasmullie/post-to-email#1]
I've deployed it on a PaaS, using the configuration tutorial for Render. When I fill a form, the email is not sent to the RECIPIENT address. There are no errors, nothing. 

The only log related to it is:

"POST /?SUBJECT=Contact HTTP/1.1" 302 3824 "https://**************/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0"

I've hidden the link with ***.

I've tested the smtp config separately, and the emails are sent (both gmail and outlook).

**Comment by liviust** [comment]
The issue stemmed from a misunderstanding of the instructions provided at [https://github.com/matthiasmullie/post-to-email/blob/main/instructions/2-form.md](https://github.com/matthiasmullie/post-to-email/blob/main/instructions/2-form.md). In the given example, 'SENDER' is designated to store the email address of the individual submitting the form, yet it concurrently serves as the SMTP user. I believe that the example should be revised to use 'REPLY_TO' in the frontend instead of 'SENDER' and set 'SENDER' within the environment variables. This adjustment would align more coherently with the intended functionality.

**Comment by matthiasmullie** [comment]
Hi @liviust - I'm glad you worked it out!

I wanted to keep the docs as simple as possible, but I guess the oversimplification made it confusing. I went ahead and added REPLY_TO in there as well, per your suggestion. Thanks!
